apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'heartbeat'
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_namespace]
            action: keep
            regex: heartbeat
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: heartbeat

      - job_name: 'pos'
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_namespace]
            action: keep
            regex: pos
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: pos

      - job_name: 'timeclock'
        metrics_path: /metrics
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_namespace]
            action: keep
            regex: timeclock
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: timeclock
