apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: timeclock
  namespace: timeclock

resources:
  - ../../base

patchesStrategicMerge:
  - patch.yaml

images:
- name: ghcr.io/bartr/heartbeat
  newTag: 0.4.0
