apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: heartbeat
  namespace: heartbeat
  annotations:
    version: v0.1.0
    expression: /c/*

resources:
- ../../base

images:
- name: ghcr.io/bartr/heartbeat
  newTag: 0.1.0
