apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: heartbeat
  namespace: heartbeat
  annotations:
    version: v0.4.0
    description: Heartbeat App
    expression: /m/ring/0

resources:
  - ../../base/ns.yaml
  - ../../base/service.yaml
  - deployment.yaml

images:
- name: ghcr.io/bartr/heartbeat
  newTag: 0.4.0
