apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: pos
  namespace: pos

resources:
  - ../../base

patchesStrategicMerge:
  - patch.yaml

images:
- name: ghcr.io/bartr/pos
  newTag: 0.4.0
