apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: pos
  namespace: pos
  annotations:
    #expression: /m/ring/0
    version: v0.4.0

resources:
- ../../base/ns.yaml
- ../../base/service.yaml
- deployment.yaml

images:
- name: ghcr.io/bartr/pos
  newTag: 0.4.0
