kind: Cluster
name: tx-bastrop
metadata:
  city: Bastrop
  county: Bastrop
  description: TX Bastrop
  areaCode: 512
  latitude: 30.11
  oven: ACME3000
  longitude: -97.3
  population: 30080
  region: Central
  ring: 2
  state: TX
  storeNumber: 78602
  timezone: America/Chicago
  type: store
---
kind: Cluster
name: tx-dale
metadata:
  city: Dale
  county: Caldwell
  description: TX Dale
  areaCode: 512
  latitude: 29.93
  oven: ACME3000
  longitude: -97.55
  population: 10530
  region: Central
  ring: 2
  state: TX
  storeNumber: 78616
  timezone: America/Chicago
  type: store
---
kind: Cluster
name: tx-del-valle
metadata:
  city: Del Valle
  county: Travis
  description: TX Del Valle
  areaCode: 512
  latitude: 30.16
  oven: ACME3000
  longitude: -97.6
  population: 25210
  region: Central
  ring: 2
  state: TX
  storeNumber: 78617
  timezone: America/Chicago
  type: store
---
kind: Cluster
name: tx-dripping-springs
metadata:
  city: Dripping Springs
  county: Hays
  description: TX Dripping Springs
  areaCode: 512
  latitude: 30.18
  oven: ACME3000
  longitude: -98.08
  population: 22250
  region: Central
  ring: 2
  state: TX
  storeNumber: 78620
  timezone: America/Chicago
  type: store
---
kind: Cluster
name: tx-elgin
metadata:
  city: Elgin
  county: Bastrop
  description: TX Elgin
  areaCode: 512
  latitude: 30.34
  oven: ACME3000
  longitude: -97.37
  population: 26550
  region: Central
  ring: 2
  state: TX
  storeNumber: 78621
  timezone: America/Chicago
  type: store
---
kind: Cluster
name: tx-fredericksburg
metadata:
  city: Fredericksburg
  county: Gillespie
  description: TX Fredericksburg
  areaCode: 325
  latitude: 30.27
  oven: ACME3000
  longitude: -98.87
  population: 22120
  region: Central
  ring: 2
  state: TX
  storeNumber: 78624
  timezone: America/Chicago
  type: store
---
kind: Cluster
name: tx-gonzales
metadata:
  type: store
  ring: 2
  storeNumber: 78629
  timezone: America/Chicago
  region: Central
  state: TX
  county: Gonzales
  city: Gonzales
  description: TX Gonzales
  areaCode: 361
  population: 11280
  oven: ACME3000
  latitude: 29.5
  longitude: -97.44
---
kind: Cluster
name: tx-leander
metadata:
  type: store
  ring: 2
  storeNumber: 78641
  timezone: America/Chicago
  region: Central
  state: TX
  county: Williamson
  city: Leander
  description: TX Leander
  areaCode: 512
  population: 88850
  oven: ACME3000
  latitude: 30.56
  longitude: -97.86
---
kind: Cluster
name: tx-liberty-hill
metadata:
  type: store
  ring: 2
  storeNumber: 78642
  timezone: America/Chicago
  region: Central
  state: TX
  county: Williamson
  city: Liberty Hill
  description: TX Liberty Hill
  areaCode: 512
  population: 23930
  oven: ACME3000
  latitude: 30.66
  longitude: -97.92
---
kind: Cluster
name: tx-lockhart
metadata:
  type: store
  ring: 2
  storeNumber: 78644
  timezone: America/Chicago
  region: Central
  state: TX
  county: Caldwell
  city: Lockhart
  description: TX Lockhart
  areaCode: 512
  population: 18020
  oven: ACME3000
  latitude: 29.87
  longitude: -97.67
