kind: Cluster
name: tx-austin
metadata:
  city: Austin
  county: Travis
  description: TX Austin
  areaCode: 512
  latitude: 30.25
  oven: ACME4000
  longitude: -97.85
  population: 50000
  region: Central
  ring: 0
  state: TX
  storeNumber: 78727
  timezone: America/Chicago
  type: store
---
kind: Cluster
name: tx-cedar-park
metadata:
  city: Cedar Park
  county: Williamson
  description: TX Cedar Park
  areaCode: 512
  latitude: 30.51
  oven: ACME3000
  longitude: -97.83
  population: 81490
  region: Central
  ring: 0
  state: TX
  storeNumber: 78613
  timezone: America/Chicago
  type: store
---
kind: Cluster
name: tx-georgetown
metadata:
  type: store
  ring: 0
  storeNumber: 78628
  timezone: America/Chicago
  region: Central
  state: TX
  county: Williamson
  city: Georgetown
  description: TX Georgetown
  areaCode: 512
  population: 43030
  oven: ACME3000
  latitude: 30.65
  longitude: -97.75
---
kind: Cluster
name: tx-pflugerville
metadata:
  type: store
  ring: 0
  storeNumber: 78660
  timezone: America/Chicago
  region: Central
  state: TX
  county: Travis
  city: Pflugerville
  description: TX Pflugerville
  areaCode: 512
  population: 106660
  oven: ACME4000
  latitude: 30.44
  longitude: -97.62
---
kind: Cluster
name: tx-round-rock
metadata:
  type: store
  ring: 0
  storeNumber: 78665
  timezone: America/Chicago
  region: Central
  state: TX
  county: Williamson
  city: Round Rock
  description: TX Round Rock
  areaCode: 512
  population: 58710
  oven: ACME4000
  latitude: 30.54
  longitude: -97.64
