apiVersion: apps/v1
kind: Deployment
metadata:
  name: timeclock
  namespace: timeclock
  labels:
    app.kubernetes.io/name: timeclock
    goa.name: tx-gonzales
    goa.ring: "2"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1
  selector:
    matchLabels:
      app: timeclock
  template:
    metadata:
      labels:
        app: timeclock
    spec:
      containers:
        - name: app
          image: ghcr.io/bartr/heartbeat:0.1.0
          imagePullPolicy: Always
          args:
          - -u
          - timeclock
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            failureThreshold: 10
            periodSeconds: 60
          resources:
            limits:
              cpu: 1000m
              memory: 2048Mi
            requests:
              cpu: 500m
              memory: 1024Mi
