apiVersion: v1
kind: Service
metadata:
  name: timeclock
  namespace: timeclock
spec:
  selector:
    app: timeclock
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
